services:
  reverse-proxy:
    image: traefik:v2.5
    command:
      - "--providers.docker"
      - "--providers.file.directory=/configuration/"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  frontend:
    build: ./frontend
    labels:
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
    restart: unless-stopped
  couchdb:
    image: couchdb:3
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    labels:
      - "traefik.http.routers.backend.rule=PathPrefix(`/db`)"
      - "traefik.http.routers.backend.middlewares=backend-stripprefix"
      - "traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/db"
      - "traefik.http.services.backend.loadbalancer.server.port=5984"
    ports:
      - '5984:5984'
    restart: unless-stopped
    volumes:
      - ./couchdb/etc/config.ini:/opt/couchdb/etc/local.d/config.ini
      - couchdb_data:/opt/couchdb/data/
volumes:
  couchdb_data:
    driver: local
